server:
  port: 8089
  servlet:
    context-path: /sso
gang:
  database:
    url: 127.0.0.1
    username: root
    password: 123456
  common:
    swagger:
      basePackage: "com.gang"
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${gang.database.url}:3306/antsso?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: ${gang.database.username}
    continue-on-error: true
    sql-script-encoding: UTF-8
    password: ${gang.database.password}
    data-username: ${gang.database.username}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      allow-pool-suspension: true
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: application-vcode.yml
  redis:
    database: 8
    host: 127.0.0.1
    password: ''
    port: 6379
ant:
  common:
    config:
      cache:
        type: redis
  sso:
    auth:
      settingList:
        - filter: com.gang.antsso.database.filter.DatabaseAuthenticationFilter
          provider: com.gang.antsso.database.provider.DatabaseAuthenticationProvider
          token: com.gang.antsso.database.token.DatabaseUserToken
        - filter: com.gang.antsso.wechat.filter.WechatAuthenticationFilter
          provider: com.gang.antsso.wechat.provider.WechatAuthenticationProvider
          token: com.gang.antsso.wechat.token.WehatUserToken
      open-auth:
    view:
      viewMap:
        login: login
        loginSms: login_sms
        loginEmail: login_email
